name: Node

concurrency:
    group: node-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    node:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16, 18, 19]

        steps:
            - uses: actions/checkout@v3.3.0
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.17.1
                  run_install: |
                      - recursive: true
                        args: [
                          --child-concurrency=9999,
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --network-concurrency=9999,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v3.6.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml
            - run: pnpm install
              working-directory: .

            - run: pnpm run build
              working-directory: .
